=== hetau/cycle/src/configuration_files/deviceconfig.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT DEVICECONFIGURATION (DESCRIPTION,DEVCLASS,REG*)>

<!ELEMENT DESCRIPTION (NAME,VERSION,AUTHOR,COMPANY,DATE,OBS)>

<!ELEMENT NAME (#PCDATA)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT AUTHOR (#PCDATA)>
<!ELEMENT COMPANY (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT OBS (#PCDATA)>


<!ELEMENT DEVCLASS EMPTY>
<!ELEMENT REG (#PCDATA)>

<!ATTLIST DEVCLASS name CDATA #REQUIRED number CDATA #REQUIRED>

=== hetau/cycle/src/opbdevices/opbuartlite/opbuartlite.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DEVICECONFIGURATION SYSTEM "deviceconfig.dtd">
<DEVICECONFIGURATION>
	<DESCRIPTION>
		<NAME>OPB UART Lite</NAME>
		<VERSION>1.00b</VERSION>
		<AUTHOR>João Ferreira</AUTHOR>
		<COMPANY>Alentejo, S.A.</COMPANY>
		<DATE>26/05/2014</DATE>
		<OBS>Test System</OBS>
	</DESCRIPTION>
	<DEVCLASS name="opbuartlite" number="4"/>
	<REG>control</REG>
	<REG>status</REG>
	<REG>rx</REG>
	<REG>tx</REG>
</DEVICECONFIGURATION>

=== hetau/cycle/src/opbdevices/opbtimercounter/opbtimercounter.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DEVICECONFIGURATION SYSTEM "deviceconfig.dtd">
<DEVICECONFIGURATION>
	<DESCRIPTION>
		<NAME>OPB Timer/Counter</NAME>
		<VERSION>1.00b</VERSION>
		<AUTHOR>João Ferreira</AUTHOR>
		<COMPANY>Alentejo, S.A.</COMPANY>
		<DATE>26/05/2014</DATE>
		<OBS>Test system</OBS>
	</DESCRIPTION>
	<DEVCLASS name="opbtimercounter" number="6"/>
	<REG>tcsr0</REG>
	<REG>tcsr1</REG>
	<REG>tlr0</REG>
	<REG>tlr1</REG>
	<REG>tcr0</REG>
	<REG>tcr1</REG>
</DEVICECONFIGURATION>
